# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-action-network
  - jekyll-sitemap

collections:
  petitions:
    output: true
  events:
    output: true
  event_campaigns:
    output: true
  campaigns:
    output: true
  forms:
    output: true

# Action Network Import
action_network:
  key: ENV_ACTION_NETWORK_API
  actions: true
  events: true
  petitions: true
  event_campaigns: true
  campaigns: true
  advocacy_campaigns:
    collection: letters
    filters:
      type: email
  forms: true
  # advocacy_campaigns:
  #   collection: call_campaigns
  #   filters:
  #     type: call
  # petitions:
  #   collection: petitions
  #   layout: an-petition 
  #   content: description
  #   mappings:
  #     title: title
  #     description: description
  #     petition_text: petition_text
  #     browser_url: browser_url
  #     featured_image_url: image
  #     target: target
  #     "action_network:sponsor": sponsor
  # campaigns:
  #   collection: campaigns
  #   layout: an-campaigns
  #   content: description
  #   mappings:
  #     title: title
  #     description: description
  #     browser_url: browser_url
  #     featured_image_url: image
  #     actions: actions
  #     "action_network:sponsor": sponsor
  # events:
  #   collection: events
  #   layout: an-event
  #   content: description
  #   mappings:
  #     title: title
  #     description: description
  #     browser_url: browser_url
  #     featured_image_url: image
  #     start_date: start_date
  #     end_date: end_date
  #     location: location
  #     "action_network:event_campaign_id": event_campaign_id
  #     status: status
  #     visibility: visibility
  #     capacity: capacity
  #     "action_network:sponsor": sponsor
  # event_campaigns:
  #   collection: event_campaigns
  #   layout: an-event_campaigns
  #   content: description
  #   mappings:
  #     title: title
  #     description: description
  #     browser_url: browser_url
  #     featured_image_url: image
  #     host_url: host_url
  #     total_events: total_events
  #     total_rsvps: total_rsvps
  #     "action_network:sponsor": sponsor
  # forms:
  #   collection: forms
  #   layout: an-forms
  #   content: description
  #   mappings:
  #     title: title
  #     description: description
  #     call_to_action: call_to_action
  #     browser_url: browser_url
  #     featured_image_url: image
  #     "action_network:sponsor": sponsor

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
